# Generated by Django 5.1.4 on 2026-05-21 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRegularization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('requested_in_time', models.TimeField(blank=True, null=True)),
                ('requested_out_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularizations', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'attendance_regularizations',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_in_minutes', models.PositiveSmallIntegerField(default=0)),
                ('grace_out_minutes', models.PositiveSmallIntegerField(default=0)),
                ('break_duration_minutes', models.PositiveSmallIntegerField(default=0)),
                ('half_day_threshold_minutes', models.PositiveSmallIntegerField(default=240)),
                ('full_day_threshold_minutes', models.PositiveSmallIntegerField(default=360)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('overtime_applicable', models.BooleanField(default=True)),
                ('overtime_after_minutes', models.PositiveSmallIntegerField(default=480)),
                ('weekly_off_days', models.CharField(default='saturday,sunday', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'shifts',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField()),
                ('log_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out')], max_length=20)),
                ('source', models.CharField(choices=[('mobile', 'Mobile App'), ('web', 'Web'), ('biometric', 'Biometric'), ('manual', 'Manual')], default='mobile', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_within_fence', models.BooleanField(null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_logs', to='employees.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.officelocation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'attendance_logs',
                'indexes': [models.Index(fields=['employee', 'log_time'], name='attendance__employe_108f47_idx'), models.Index(fields=['tenant', 'log_time'], name='attendance__tenant__d51781_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_working_days', models.PositiveSmallIntegerField(default=0)),
                ('present_days', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('absent_days', models.PositiveSmallIntegerField(default=0)),
                ('half_days', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('on_leave_days', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('holiday_days', models.PositiveSmallIntegerField(default=0)),
                ('week_off_days', models.PositiveSmallIntegerField(default=0)),
                ('lop_days', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('late_arrivals', models.PositiveSmallIntegerField(default=0)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'monthly_attendance_summary',
                'unique_together': {('tenant', 'employee', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employees.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.shift')),
            ],
            options={
                'db_table': 'employee_shift_assignments',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['employee', 'effective_date'], name='employee_sh_employe_c8b022_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('first_in_time', models.DateTimeField(blank=True, null=True)),
                ('last_out_time', models.DateTimeField(blank=True, null=True)),
                ('total_working_minutes', models.PositiveSmallIntegerField(default=0)),
                ('break_minutes', models.PositiveSmallIntegerField(default=0)),
                ('net_working_minutes', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('holiday', 'Holiday'), ('week_off', 'Week Off'), ('on_duty', 'On Duty'), ('wfh', 'Work From Home'), ('lop', 'Loss of Pay')], max_length=20)),
                ('overtime_minutes', models.PositiveSmallIntegerField(default=0)),
                ('late_by_minutes', models.PositiveSmallIntegerField(default=0)),
                ('is_regularized', models.BooleanField(default=False)),
                ('regularization_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenants.tenant')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift')),
            ],
            options={
                'db_table': 'attendance_records',
                'indexes': [models.Index(fields=['tenant', 'attendance_date'], name='attendance__tenant__5fb388_idx'), models.Index(fields=['employee', 'attendance_date'], name='attendance__employe_31915a_idx')],
                'unique_together': {('tenant', 'employee', 'attendance_date')},
            },
        ),
    ]
