# Generated by Django 5.0.6 on 2026-05-25 17:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('masters', '0003_costcenter_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('salvage_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('method', models.CharField(choices=[('SLM', 'Straight Line'), ('WDV', 'Written Down Value')], default='SLM', max_length=10)),
                ('useful_life_years', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('wdv_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('current_book_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('last_depreciated', models.DateField(blank=True, null=True)),
                ('is_disposed', models.BooleanField(default=False)),
                ('accum_depr_account', models.ForeignKey(help_text='Accumulated Depreciation account', on_delete=django.db.models.deletion.PROTECT, related_name='accum_depr_for', to='masters.account')),
                ('asset_account', models.ForeignKey(help_text='Asset GL account (1210, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='masters.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='masters.company')),
                ('expense_account', models.ForeignKey(help_text='Depreciation expense account', on_delete=django.db.models.deletion.PROTECT, related_name='depr_expense_for', to='masters.account')),
            ],
            options={
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalFixedAsset',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('salvage_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('method', models.CharField(choices=[('SLM', 'Straight Line'), ('WDV', 'Written Down Value')], default='SLM', max_length=10)),
                ('useful_life_years', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('wdv_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('current_book_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('last_depreciated', models.DateField(blank=True, null=True)),
                ('is_disposed', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('accum_depr_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Accumulated Depreciation account', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.account')),
                ('asset_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Asset GL account (1210, etc.)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.account')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.company')),
                ('expense_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Depreciation expense account', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fixed asset',
                'verbose_name_plural': 'historical fixed assets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.journalentry')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciations', to='assets.fixedasset')),
            ],
            options={
                'ordering': ('period_end',),
                'unique_together': {('asset', 'period_end')},
            },
        ),
    ]
