# Generated by Django 5.0.6 on 2026-05-25 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('masters', '0003_costcenter_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_no', models.CharField(db_index=True, max_length=40)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='masters.item')),
            ],
            options={
                'unique_together': {('item', 'batch_no')},
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='masters.company')),
            ],
            options={
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_no', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(default='IN_STOCK', help_text='IN_STOCK / SOLD / SCRAPPED', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='masters.item')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('item', 'serial_no')},
            },
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('OPENING', 'Opening Balance'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('XFER_OUT', 'Transfer Out'), ('XFER_IN', 'Transfer In'), ('ADJUST', 'Adjustment'), ('SCRAP', 'Scrap'), ('RTN_IN', 'Sales Return In'), ('RTN_OUT', 'Purchase Return Out')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('reference', models.CharField(blank=True, help_text='Linked voucher (Invoice, Bill, etc.)', max_length=80)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.batch')),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.bin')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='masters.item')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.journalentry')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.serialnumber')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse')),
            ],
            options={
                'ordering': ('-date', '-id'),
                'indexes': [models.Index(fields=['item', 'warehouse'], name='inventory_s_item_id_3d2f9a_idx'), models.Index(fields=['date', 'kind'], name='inventory_s_date_029d31_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('avg_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('reorder_level', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='masters.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('item', 'warehouse')},
            },
        ),
    ]
