# Generated by Django 5.1.4 on 2026-05-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tan',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
