# Generated by Django 5.1.4 on 2026-06-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_product_entitlements'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
