# Generated by Django 5.1.4 on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_tenant_payroll_jurisdiction"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="ui_language",
            field=models.CharField(
                choices=[("en", "English"), ("ar", "Arabic")],
                default="en",
                max_length=5,
            ),
        ),
    ]
