# Generated by Django 5.0.6 on 2026-05-25 12:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hsn_codes', to='masters.company')),
            ],
            options={
                'verbose_name': 'HSN/SAC code',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('sku', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('GOODS', 'Goods'), ('SERVICE', 'Service')], default='GOODS', max_length=10)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('unit', models.CharField(default='Nos', help_text='UoM, e.g. Nos, Kg, Hrs', max_length=20)),
                ('sale_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('purchase_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='GST rate %. If 0, uses HSN default.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hsn', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.hsncode')),
            ],
            options={
                'verbose_name': 'historical item',
                'verbose_name_plural': 'historical items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('GOODS', 'Goods'), ('SERVICE', 'Service')], default='GOODS', max_length=10)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('unit', models.CharField(default='Nos', help_text='UoM, e.g. Nos, Kg, Hrs', max_length=20)),
                ('sale_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('purchase_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='GST rate %. If 0, uses HSN default.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='masters.company')),
                ('hsn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.hsncode')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('company', 'sku')},
            },
        ),
    ]
