# Generated by Django 5.0.6 on 2026-06-03 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_numberseries'),
        ('procurement', '0002_historicalvendorbill_last_reminder_at_and_more'),
        ('taxation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDSDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('194C', '194C – Contractor / Sub-contractor (1% individual, 2% others)'), ('194J', '194J – Professional / Technical Services (10%)'), ('194H', '194H – Commission / Brokerage (5%)'), ('194I', '194I – Rent (10% plant/machinery, 10% land/building)'), ('194A', '194A – Interest other than securities (10%)'), ('194B', '194B – Lottery / Puzzle (30%)'), ('194D', '194D – Insurance Commission (5%)'), ('194Q', '194Q – Purchase of Goods above ₹50L (0.1%)'), ('194R', '194R – Perquisite / Benefit to Resident (10%)'), ('195', '195 – Payment to Non-Resident (rates vary)'), ('OTHER', 'Other Section')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('base_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tds_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('deduction_date', models.DateField()),
                ('pan', models.CharField(blank=True, help_text='Vendor PAN', max_length=10)),
                ('fy', models.CharField(help_text='e.g. 2025-26', max_length=7)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 (Apr–Jun)'), ('Q2', 'Q2 (Jul–Sep)'), ('Q3', 'Q3 (Oct–Dec)'), ('Q4', 'Q4 (Jan–Mar)')], max_length=2)),
                ('challan_no', models.CharField(blank=True, max_length=40)),
                ('deposited_date', models.DateField(blank=True, null=True)),
                ('is_deposited', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tds_deductions', to='masters.company')),
                ('vendor_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_deductions', to='procurement.vendorbill')),
            ],
            options={
                'ordering': ('-deduction_date',),
            },
        ),
    ]
