# Generated by Django 5.0.6 on 2026-06-20 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_creditnote_vat_historicalcreditnote_vat_and_more'),
        ('masters', '0008_company_country_company_standard_vat_rate_and_more'),
        ('taxation', '0002_tdsdeduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GccEInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.CharField(choices=[('ZATCA', 'KSA ZATCA Fatoora'), ('PEPPOL_PINT_AE', 'UAE Peppol PINT AE')], max_length=16)),
                ('uuid', models.CharField(db_index=True, max_length=64)),
                ('invoice_hash', models.CharField(blank=True, max_length=128)),
                ('previous_hash', models.CharField(blank=True, help_text='PIH — previous invoice hash (ZATCA chain)', max_length=128)),
                ('xml', models.TextField(blank=True)),
                ('qr', models.TextField(blank=True, help_text='ZATCA base64 TLV QR payload')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('CLEARED', 'Cleared'), ('REPORTED', 'Reported'), ('FAILED', 'Failed')], default='GENERATED', max_length=12)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, help_text='Gateway / ASP response')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcc_einvoice', to='billing.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
