# Generated by Django 5.1.4 on 2026-05-21 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('responsible_party', models.CharField(choices=[('hr', 'HR'), ('employee', 'Employee'), ('it', 'IT'), ('manager', 'Manager'), ('finance', 'Finance')], max_length=20)),
                ('due_days_offset', models.SmallIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('sequence_order', models.PositiveSmallIntegerField(default=50)),
            ],
            options={
                'db_table': 'onboarding_tasks',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='tenants.tenant')),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Under Maintenance'), ('disposed', 'Disposed')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['name'],
                'unique_together': {('tenant', 'asset_code')},
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('condition_on_assign', models.CharField(default='good', max_length=20)),
                ('condition_on_return', models.CharField(blank=True, max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr_ops.asset')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_assets', to='employees.employee')),
            ],
            options={
                'db_table': 'asset_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'employee_onboarding',
            },
        ),
        migrations.CreateModel(
            name='ExitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_date', models.DateField()),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('exit_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('interview_scheduled', models.BooleanField(default=False)),
                ('fnf_cleared', models.BooleanField(default=False)),
                ('assets_returned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_request', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'exit_requests',
            },
        ),
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('experience', 'Experience Letter'), ('relieving', 'Relieving Letter'), ('offer', 'Offer Letter'), ('increment', 'Increment Letter'), ('warning', 'Warning Letter'), ('appreciation', 'Appreciation Letter'), ('appointment', 'Appointment Letter'), ('custom', 'Custom')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('template_html', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'letter_templates',
                'ordering': ['letter_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HRLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='hr_letters/%Y/')),
                ('is_shared', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_letters', to='employees.employee')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_ops.lettertemplate')),
            ],
            options={
                'db_table': 'hr_letters',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hr_ops.employeeonboarding')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_ops.onboardingtask')),
            ],
            options={
                'db_table': 'onboarding_items',
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'onboarding_templates',
            },
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hr_ops.onboardingtemplate'),
        ),
        migrations.AddField(
            model_name='employeeonboarding',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_ops.onboardingtemplate'),
        ),
    ]
