# Generated by Django 5.0.6 on 2026-06-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljournalentry',
            name='category',
            field=models.CharField(choices=[('sales', 'Sales Invoice'), ('purchase', 'Vendor Bill'), ('receipt', 'Customer Receipt'), ('payment', 'Vendor Payment'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='category',
            field=models.CharField(choices=[('sales', 'Sales Invoice'), ('purchase', 'Vendor Bill'), ('receipt', 'Customer Receipt'), ('payment', 'Vendor Payment'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=20),
        ),
    ]
