# Generated by Django 5.1.4 on 2026-05-24 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_ops', '0002_notification'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('publish', 'Published'), ('submit', 'Submitted'), ('login', 'Logged in'), ('logout', 'Logged out'), ('export', 'Exported'), ('view', 'Viewed'), ('other', 'Other')], max_length=30)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('resource_label', models.CharField(blank=True, max_length=255)),
                ('summary', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='audit_logs_tenant__0b1a88_idx'), models.Index(fields=['tenant', 'resource_type', 'created_at'], name='audit_logs_tenant__a1ee4c_idx'), models.Index(fields=['actor', 'created_at'], name='audit_logs_actor_i_5bd818_idx')],
            },
        ),
    ]
