# Generated by Django 5.1.4 on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_ops", "0008_companycalendarevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="exitrequest",
            name="settlement_amount",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="exitrequest",
            name="settlement_computed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exitrequest",
            name="settlement_label",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="exitrequest",
            name="settlement_note",
            field=models.TextField(blank=True),
        ),
    ]
