# Generated by Django 5.1.4 on 2026-06-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_ops', '0018_notification_seat_limit_types'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companydocument',
            new_name='company_doc_tenant__e8f5fd_idx',
            old_name='company_doc_tenant__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='companydocumentaccessrequest',
            new_name='company_doc_tenant__882e13_idx',
            old_name='company_req_tenant__d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='companydocumentaccessrequest',
            new_name='company_doc_employe_a05e97_idx',
            old_name='company_req_employe_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='hrletter',
            new_name='hr_letters_tenant__341053_idx',
            old_name='hr_letters_tenant__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='hrletter',
            new_name='hr_letters_tenant__b8f2b3_idx',
            old_name='hr_letters_tenant__d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='hrletter',
            new_name='hr_letters_tenant__4d1780_idx',
            old_name='hr_letters_tenant__rec_offer_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('publish', 'Published'), ('submit', 'Submitted'), ('issue', 'Issued'), ('download', 'Downloaded'), ('email', 'Emailed'), ('duplicate', 'Duplicated'), ('regenerate', 'Regenerated'), ('login', 'Logged in'), ('logout', 'Logged out'), ('export', 'Exported'), ('view', 'Viewed'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='letter_type',
            field=models.CharField(choices=[('offer', 'Offer Letter'), ('intent', 'Letter of Intent (LOI)'), ('appointment', 'Appointment Letter'), ('experience', 'Experience Letter'), ('relieving', 'Relieving Letter'), ('promotion', 'Promotion Letter'), ('increment', 'Salary Increment Letter'), ('warning', 'Warning Letter'), ('confirmation', 'Confirmation Letter'), ('termination', 'Termination Letter'), ('internship', 'Internship Letter'), ('appreciation', 'Appreciation Letter'), ('noc', 'No Objection Certificate (NOC)'), ('certificate', 'Certificate'), ('custom', 'Custom')], max_length=30),
        ),
    ]
