# Generated by Django 5.0.6 on 2026-06-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_historicalvendorbill_last_reminder_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorbill',
            name='vat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='vat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorbillline',
            name='supply_type',
            field=models.CharField(choices=[('STANDARD', 'Standard-rated'), ('ZERO_RATED', 'Zero-rated'), ('EXEMPT', 'Exempt')], default='STANDARD', help_text='GCC VAT supply type. Ignored under India GST.', max_length=12),
        ),
        migrations.AddField(
            model_name='vendorbillline',
            name='vat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
