# Generated by Django 5.1.4 on 2026-06-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_historicalvendorbill_vat_vendorbill_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorbill',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalvendorbill',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='1 unit of `currency` = this many base-currency units. 1 when currency == base.', max_digits=18),
        ),
        migrations.AddField(
            model_name='historicalvendorpayment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalvendorpayment',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='1 unit of `currency` = this many base-currency units. 1 when currency == base.', max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='1 unit of `currency` = this many base-currency units. 1 when currency == base.', max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='1 unit of `currency` = this many base-currency units. 1 when currency == base.', max_digits=18),
        ),
    ]
