# Generated by Django 5.0.6 on 2026-05-25 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_historicalinvoice_currency_historicalinvoice_fx_rate_and_more'),
        ('masters', '0003_costcenter_project'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceIRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('irn', models.CharField(db_index=True, max_length=64)),
                ('ack_no', models.CharField(blank=True, max_length=40)),
                ('ack_date', models.DateTimeField(blank=True, null=True)),
                ('signed_qr', models.TextField()),
                ('signed_invoice', models.TextField(blank=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='einvoice', to='billing.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eway_no', models.CharField(db_index=True, max_length=40)),
                ('generated_on', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('distance_km', models.IntegerField()),
                ('vehicle_no', models.CharField(blank=True, max_length=20)),
                ('transporter_id', models.CharField(blank=True, max_length=20)),
                ('transporter_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eway_bills', to='billing.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GSTR2BLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_period', models.CharField(db_index=True, help_text='MMYYYY', max_length=7)),
                ('supplier_gstin', models.CharField(db_index=True, max_length=15)),
                ('supplier_name', models.CharField(max_length=255)),
                ('invoice_no', models.CharField(max_length=40)),
                ('invoice_date', models.DateField()),
                ('taxable', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cgst', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('sgst', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('igst', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('DISPUTED', 'Disputed')], default='UNMATCHED', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
                ('matched_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gstr2b_matches', to='procurement.vendorbill')),
            ],
            options={
                'unique_together': {('company', 'return_period', 'supplier_gstin', 'invoice_no')},
            },
        ),
    ]
