# Generated by Django 5.0.6 on 2026-06-03 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger', models.CharField(choices=[('invoice_overdue', 'Invoice Overdue'), ('invoice_paid', 'Invoice Paid'), ('new_invoice', 'New Invoice Posted'), ('vendor_bill_due', 'Vendor Bill Due Soon'), ('low_stock', 'Item Below Reorder Level'), ('monthly_report', 'Monthly Report (1st of month)')], max_length=40)),
                ('trigger_filter', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(choices=[('send_email', 'Send Email'), ('send_notification', 'In-App Notification'), ('webhook', 'HTTP Webhook'), ('whatsapp', 'WhatsApp Message')], max_length=40)),
                ('action_config', models.JSONField(default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='success', max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.automationrule')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
