# Generated by Django 5.0.6 on 2026-05-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_historicalinvoice_currency_historicalinvoice_fx_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, help_text='Last overdue reminder sent', null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='reminder_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, help_text='Last overdue reminder sent', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_count',
            field=models.IntegerField(default=0),
        ),
    ]
