# Generated by Django 5.0.6 on 2026-06-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_subscription_entitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasinvoice',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saasinvoice',
            name='customer_gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='saasinvoice',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saasinvoice',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='saasinvoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='saasinvoice',
            name='sac_code',
            field=models.CharField(default='9983', max_length=10),
        ),
        migrations.AddField(
            model_name='saasinvoice',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saasinvoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AddField(
            model_name='saasinvoice',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
