# Generated by Django 5.1.4 on 2026-06-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_processedwebhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
