# Generated by Django 5.1.4 on 2026-06-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_subscription_razorpay_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(db_index=True, max_length=254)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_schema', models.CharField(blank=True, db_index=True, max_length=63)),
                ('target_label', models.CharField(blank=True, max_length=200)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
