# Generated by Django 5.0.6 on 2026-05-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_costcenter_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparty',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Beneficiary name as per bank records', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='party',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Beneficiary name as per bank records', max_length=200),
        ),
        migrations.AddField(
            model_name='party',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='party',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='party',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='party',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='party',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
