# Generated by Django 5.0.6 on 2026-06-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_historicalparty_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='setup_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
