# Generated by Django 5.0.6 on 2026-06-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_company_setup_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('invoice', 'Tax Invoice'), ('credit_note', 'Credit Note'), ('quotation', 'Quotation'), ('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order'), ('vendor_bill', 'Vendor Bill'), ('receipt', 'Customer Receipt'), ('vendor_payment', 'Vendor Payment')], max_length=20)),
                ('prefix', models.CharField(blank=True, default='', help_text='e.g. INV- or INV/2025/', max_length=20)),
                ('padding', models.PositiveSmallIntegerField(default=4, help_text='Zero-pad the running number to this width')),
                ('start_number', models.PositiveIntegerField(default=1, help_text='First number to use when none exist yet')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_series', to='masters.company')),
            ],
            options={
                'verbose_name_plural': 'Number series',
                'unique_together': {('company', 'doc_type')},
            },
        ),
    ]
