# Generated by Django 5.0.6 on 2026-06-03 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_numberseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham'), ('SGD', 'Singapore Dollar'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, help_text='1 unit = X INR', max_digits=18)),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(default='manual', help_text='manual | rbi | fixer', max_length=40)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='masters.company')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('company', 'currency', 'date')},
            },
        ),
    ]
