# Generated by Django 5.0.6 on 2026-06-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='IN', help_text='ISO country code', max_length=2),
        ),
        migrations.AddField(
            model_name='company',
            name='standard_vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standard VAT rate for the jurisdiction (GCC). Unused for India GST.', max_digits=5),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, help_text='VAT registration number (TRN) for GCC. GSTIN stays in its own field for India.', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_regime',
            field=models.CharField(choices=[('INDIA_GST', 'India — GST'), ('GCC_VAT', 'GCC — VAT'), ('NONE', 'No indirect tax')], default='INDIA_GST', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='country',
            field=models.CharField(default='IN', help_text='ISO country code', max_length=2),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='standard_vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standard VAT rate for the jurisdiction (GCC). Unused for India GST.', max_digits=5),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='tax_id',
            field=models.CharField(blank=True, help_text='VAT registration number (TRN) for GCC. GSTIN stays in its own field for India.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='tax_regime',
            field=models.CharField(choices=[('INDIA_GST', 'India — GST'), ('GCC_VAT', 'GCC — VAT'), ('NONE', 'No indirect tax')], default='INDIA_GST', max_length=12),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham'), ('SGD', 'Singapore Dollar'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('SAR', 'Saudi Riyal'), ('QAR', 'Qatari Riyal'), ('KWD', 'Kuwaiti Dinar'), ('BHD', 'Bahraini Dinar'), ('OMR', 'Omani Rial')], max_length=3),
        ),
    ]
