# Generated by Django 5.1.4 on 2026-05-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='esi_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='uan_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='esi_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='uan_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
