# Generated by Django 5.1.4 on 2026-05-25 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_esi_number_employee_uan_number_and_more'),
        ('tenants', '0002_tenant_tan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttritionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='0 (no risk) - 100 (very high)')),
                ('risk_band', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('factors', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attrition_score', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrition_scores', to='tenants.tenant')),
            ],
            options={
                'db_table': 'attrition_scores',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['tenant', '-score'], name='attrition_s_tenant__6d872b_idx'), models.Index(fields=['tenant', 'risk_band'], name='attrition_s_tenant__66a5d4_idx')],
            },
        ),
    ]
