# Generated by Django 5.1.4 on 2026-06-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_attritionscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='_civil_id_enc',
            field=models.TextField(blank=True, db_column='civil_id_enc'),
        ),
        migrations.AddField(
            model_name='employee',
            name='civil_id_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('limited', 'Limited'), ('unlimited', 'Unlimited')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_kuwaiti_national',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, help_text='ISO country code', max_length=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='pifss_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='residency_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='residency_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='sponsor_file_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='_civil_id_enc',
            field=models.TextField(blank=True, db_column='civil_id_enc'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='civil_id_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('limited', 'Limited'), ('unlimited', 'Unlimited')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='is_kuwaiti_national',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='nationality',
            field=models.CharField(blank=True, help_text='ISO country code', max_length=2),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='pifss_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='residency_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='residency_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='sponsor_file_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='work_permit_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='work_permit_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('civil_id', 'Civil ID'), ('residency', 'Residency / Iqama'), ('work_permit', 'Work Permit'), ('degree', 'Degree Certificate'), ('offer_letter', 'Offer Letter'), ('relieving', 'Relieving Letter'), ('experience', 'Experience Letter'), ('other', 'Other')], max_length=50),
        ),
    ]
