# Generated by Django 5.1.4 on 2026-06-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_preferred_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalemployee',
            name='name_ar',
            field=models.CharField(blank=True, help_text='Arabic name for GCC payslips', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='Nickname or display name shown across the company directory (optional).', max_length=80),
        ),
    ]
