# Generated by Django 5.0.6 on 2026-05-25 17:57

import apps.portal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0003_costcenter_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, default=apps.portal.models._new_token, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access', to='masters.party')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
