# Generated by Django 5.1.4 on 2026-06-18 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_alter_candidate_email_alter_candidate_first_name_and_more'),
        ('tenants', '0004_tenant_setup_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='certification_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='gaps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='qualification_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skill_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ScoringWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_weight', models.PositiveSmallIntegerField(default=40)),
                ('experience_weight', models.PositiveSmallIntegerField(default=30)),
                ('qualification_weight', models.PositiveSmallIntegerField(default=20)),
                ('certification_weight', models.PositiveSmallIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_opening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_weights', to='recruitment.jobopening')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'scoring_weights',
            },
        ),
    ]
