# Generated by Django 5.1.4 on 2026-06-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_candidateprofile_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
