# Generated by Django 5.1.4 on 2026-06-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_interview_resumeversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='positions_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
