# Generated by Django 5.1.4 on 2026-05-21 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(blank=True, max_length=50)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_installments', models.PositiveSmallIntegerField()),
                ('paid_installments', models.PositiveSmallIntegerField(default=0)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('disbursed_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'employee_loans',
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('review', 'Under Review'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('total_employees', models.PositiveIntegerField(default=0)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_employer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('run_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payroll_runs',
                'ordering': ['-year', '-month'],
                'unique_together': {('tenant', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lop_days', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('paid_days', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('working_days', models.PositiveSmallIntegerField(default=0)),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conveyance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esi_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lwf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esi_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lwf_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('earnings_detail', models.JSONField(default=dict)),
                ('deductions_detail', models.JSONField(default=dict)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'payroll_records',
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/%Y/')),
                ('expense_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('paid_in_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'expense_claims',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='payslips/%Y/%m/')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
                ('payroll_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='payroll.payrollrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'payslips',
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_contribution', 'Employer Contribution')], max_length=30)),
                ('calc_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('pct_of_basic', '% of Basic'), ('pct_of_gross', '% of Gross'), ('formula', 'Custom Formula'), ('statutory', 'Statutory (auto)')], max_length=30)),
                ('calc_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('formula', models.TextField(blank=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_statutory', models.BooleanField(default=False)),
                ('statutory_type', models.CharField(blank=True, choices=[('pf', 'Provident Fund'), ('esi', 'ESI'), ('pt', 'Professional Tax'), ('lwf', 'Labour Welfare Fund'), ('tds', 'TDS')], max_length=20)),
                ('show_on_payslip', models.BooleanField(default=True)),
                ('sequence_order', models.PositiveSmallIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='tenants.tenant')),
            ],
            options={
                'db_table': 'salary_components',
                'ordering': ['sequence_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='tenants.tenant')),
            ],
            options={
                'db_table': 'salary_structures',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('ctc_annual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic_monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('component_overrides', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarystructure')),
            ],
            options={
                'db_table': 'employee_salaries',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveSmallIntegerField(default=50)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarycomponent')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_components', to='payroll.salarystructure')),
            ],
            options={
                'db_table': 'salary_structure_components',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='components',
            field=models.ManyToManyField(blank=True, through='payroll.SalaryStructureComponent', to='payroll.salarycomponent'),
        ),
        migrations.CreateModel(
            name='StatutorySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statutory_type', models.CharField(choices=[('pf', 'Provident Fund'), ('esi', 'ESI'), ('pt', 'Professional Tax'), ('lwf', 'Labour Welfare Fund')], max_length=20)),
                ('state_code', models.CharField(blank=True, max_length=10)),
                ('employee_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('employer_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('wage_ceiling', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('slabs', models.JSONField(blank=True, default=list)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'statutory_settings',
            },
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['payroll_run'], name='payroll_rec_payroll_840031_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['employee'], name='payroll_rec_employe_a6741c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together={('payroll_run', 'employee')},
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', 'year', 'month'], name='payslips_employe_ff253d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salarycomponent',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='salarystructurecomponent',
            unique_together={('structure', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='salarystructure',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='statutorysetting',
            unique_together={('tenant', 'statutory_type', 'state_code', 'effective_date')},
        ),
    ]
