# Generated by Django 5.1.4 on 2026-05-24 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_esi_number_employee_uan_number_and_more'),
        ('payroll', '0001_initial'),
        ('tenants', '0002_tenant_tan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9)),
                ('assessment_year', models.CharField(max_length=9)),
                ('part_b_pdf', models.FileField(blank=True, null=True, upload_to='form16/part_b/%Y/')),
                ('part_a_pdf', models.FileField(blank=True, null=True, upload_to='form16/part_a/%Y/')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_exemptions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('standard_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chapter_via_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tds_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('regime', models.CharField(default='new', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_issued', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form16s', to='employees.employee')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form16s', to='tenants.tenant')),
            ],
            options={
                'db_table': 'form16',
                'ordering': ['-financial_year'],
                'unique_together': {('tenant', 'employee', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='TaxDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9)),
                ('regime', models.CharField(choices=[('new', 'New Regime (default, FY 2025-26)'), ('old', 'Old Regime (with deductions)')], default='new', max_length=10)),
                ('rent_paid_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_metro_city', models.BooleanField(default=False)),
                ('landlord_name', models.CharField(blank=True, max_length=255)),
                ('landlord_pan', models.CharField(blank=True, max_length=10)),
                ('sec_80c_ppf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sec_80c_elss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sec_80c_lic', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sec_80c_home_loan_principal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sec_80c_tuition_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sec_80c_other', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sec_80d_self', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sec_80d_parents', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sec_80d_parents_senior', models.BooleanField(default=False)),
                ('sec_80ccd_1b_nps', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sec_80e_education_loan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sec_80g_donations', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sec_24_home_loan_interest', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_income_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted (locked)'), ('verified', 'Verified by HR')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('hr_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_declarations',
                'ordering': ['-financial_year'],
                'unique_together': {('tenant', 'employee', 'financial_year')},
            },
        ),
    ]
