# Generated by Django 5.1.4 on 2026-06-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrollrecord_hr_adjustments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycomponent',
            name='statutory_type',
            field=models.CharField(blank=True, choices=[('pf', 'Provident Fund'), ('esi', 'ESI'), ('pt', 'Professional Tax'), ('lwf', 'Labour Welfare Fund'), ('tds', 'TDS'), ('pifss', 'PIFSS (Kuwait)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statutorysetting',
            name='statutory_type',
            field=models.CharField(choices=[('pf', 'Provident Fund'), ('esi', 'ESI'), ('pt', 'Professional Tax'), ('lwf', 'Labour Welfare Fund'), ('pifss', 'PIFSS (Kuwait)')], max_length=20),
        ),
    ]
