# Generated by Django 5.1.4 on 2026-06-19

from django.db import migrations, models


STATUTORY_CHOICES = [
    ("pf", "Provident Fund"),
    ("esi", "ESI"),
    ("pt", "Professional Tax"),
    ("lwf", "Labour Welfare Fund"),
    ("tds", "TDS"),
    ("pifss", "PIFSS (Kuwait)"),
    ("gosi", "GOSI (Saudi Arabia)"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0004_gcc_p1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarycomponent",
            name="statutory_type",
            field=models.CharField(blank=True, choices=STATUTORY_CHOICES, max_length=20),
        ),
        migrations.AlterField(
            model_name="statutorysetting",
            name="statutory_type",
            field=models.CharField(choices=STATUTORY_CHOICES, max_length=20),
        ),
    ]
