/**
 * Browser-side PDF generation for Tax Invoices using jsPDF + autoTable.
 * Produces a clean A4 invoice with company header, customer info, line items,
 * GST breakup, and totals. Not GST-portal grade but presentable to customers.
 */
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Invoice } from '@/features/billing/api';

export interface PdfCompany {
  name: string;
  legal_name?: string;
  gstin?: string;
  state_code?: string;
  base_currency?: string;
}

export interface PdfCustomer {
  name: string;
  gstin?: string;
  billing_address?: string;
  state_code?: string;
  email?: string;
}

function inr(n: string | number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency', currency: 'INR', maximumFractionDigits: 2,
  }).format(Number(n));
}

export function downloadInvoicePdf(inv: Invoice, company: PdfCompany, customer: PdfCustomer) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();

  // ── Header ──
  doc.setFontSize(20).setFont('helvetica', 'bold');
  doc.text('TAX INVOICE', W - 40, 40, { align: 'right' });

  doc.setFontSize(11).setFont('helvetica', 'bold');
  doc.text(company.name, 40, 50);
  doc.setFontSize(9).setFont('helvetica', 'normal').setTextColor(80);
  if (company.legal_name) doc.text(company.legal_name, 40, 65);
  if (company.gstin) doc.text(`GSTIN: ${company.gstin}`, 40, 78);
  doc.setTextColor(0);

  doc.setFontSize(9);
  doc.text(`Invoice #: ${inv.invoice_no}`, W - 40, 60, { align: 'right' });
  doc.text(`Date: ${inv.date}`, W - 40, 73, { align: 'right' });
  if (inv.due_date) doc.text(`Due: ${inv.due_date}`, W - 40, 86, { align: 'right' });

  // ── Bill to ──
  let y = 120;
  doc.setFontSize(9).setFont('helvetica', 'bold').setTextColor(120);
  doc.text('BILL TO', 40, y);
  doc.setTextColor(0).setFont('helvetica', 'normal');
  y += 13;
  doc.setFontSize(10);
  doc.text(customer.name, 40, y);
  y += 12;
  if (customer.billing_address) {
    const lines = doc.splitTextToSize(customer.billing_address, 220);
    doc.setFontSize(9).setTextColor(80);
    doc.text(lines, 40, y);
    y += lines.length * 11;
    doc.setTextColor(0);
  }
  doc.setFontSize(9);
  if (customer.gstin) { doc.text(`GSTIN: ${customer.gstin}`, 40, y); y += 11; }
  if (customer.email) { doc.text(customer.email, 40, y); y += 11; }

  doc.setFontSize(9).setTextColor(120);
  doc.text(`Place of Supply: ${inv.place_of_supply}`, W - 40, 120, { align: 'right' });
  doc.setTextColor(0);

  // ── Line items table ──
  const tableStartY = Math.max(y + 15, 200);
  autoTable(doc, {
    startY: tableStartY,
    head: [['#', 'Description', 'HSN', 'Qty', 'Rate', 'Taxable', 'CGST', 'SGST', 'IGST', 'Total']],
    body: inv.lines.map((l, i) => [
      i + 1, l.description, l.hsn_code || '—',
      l.quantity, inr(l.unit_price), inr(l.taxable_amount),
      Number(l.cgst) ? inr(l.cgst) : '—',
      Number(l.sgst) ? inr(l.sgst) : '—',
      Number(l.igst) ? inr(l.igst) : '—',
      inr(l.line_total),
    ]),
    styles: { fontSize: 8, cellPadding: 4 },
    headStyles: { fillColor: [241, 245, 249], textColor: 70, fontStyle: 'bold' },
    columnStyles: {
      0: { halign: 'center', cellWidth: 20 },
      3: { halign: 'right', cellWidth: 35 },
      4: { halign: 'right', cellWidth: 55 },
      5: { halign: 'right', cellWidth: 60 },
      6: { halign: 'right', cellWidth: 45 },
      7: { halign: 'right', cellWidth: 45 },
      8: { halign: 'right', cellWidth: 45 },
      9: { halign: 'right', cellWidth: 60, fontStyle: 'bold' },
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;

  // ── Totals box ──
  const rightX = W - 40;
  const labelX = W - 200;
  doc.setFontSize(9);
  const row = (label: string, val: string, bold = false) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.text(label, labelX, (row as any).y);
    doc.text(val, rightX, (row as any).y, { align: 'right' });
    (row as any).y += 14;
  };
  (row as any).y = finalY + 10;
  row('Taxable Amount', inr(inv.taxable_amount));
  if (Number(inv.cgst)) row('CGST', inr(inv.cgst));
  if (Number(inv.sgst)) row('SGST', inr(inv.sgst));
  if (Number(inv.igst)) row('IGST', inr(inv.igst));
  (row as any).y += 4;
  row('Grand Total', inr(inv.grand_total), true);
  row('Amount Paid', inr(inv.amount_paid));
  row('Balance Due', inr(inv.balance_due), true);

  // ── Footer ──
  if (inv.notes) {
    const ny = (row as any).y + 20;
    doc.setFontSize(9).setTextColor(120).setFont('helvetica', 'bold');
    doc.text('Notes', 40, ny);
    doc.setFont('helvetica', 'normal').setTextColor(0);
    doc.text(doc.splitTextToSize(inv.notes, W - 80), 40, ny + 12);
  }

  doc.setFontSize(8).setTextColor(150);
  doc.text(`Generated by fin-saptta • ${new Date().toLocaleString('en-IN')}`,
    W / 2, doc.internal.pageSize.getHeight() - 25, { align: 'center' });

  doc.save(`${inv.invoice_no}.pdf`);
}
