# Generated by Django 5.0.6 on 2026-05-25 17:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('masters', '0003_costcenter_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('RECEIVED', 'Received from customer'), ('PAID', 'Paid to vendor')], max_length=10)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('balance', models.DecimalField(decimal_places=4, help_text='Unadjusted portion', max_digits=18)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.journalentry')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.party')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=40)),
                ('ifsc', models.CharField(blank=True, max_length=11)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_balance', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='masters.company')),
                ('ledger_account', models.ForeignKey(help_text='The GL account this bank account posts to (e.g. 1121)', on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='masters.account')),
            ],
            options={
                'unique_together': {('company', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=4, max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=4, max_digits=18)),
                ('source', models.CharField(default='CSV', max_length=40)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='banking.bankaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalBankAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=40)),
                ('ifsc', models.CharField(blank=True, max_length=11)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_balance', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.ForeignKey(blank=True, db_constraint=False, help_text='The GL account this bank account posts to (e.g. 1121)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.account')),
            ],
            options={
                'verbose_name': 'historical bank account',
                'verbose_name_plural': 'historical bank accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PostDatedCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('ISSUED', 'Issued to vendor'), ('RECEIVED', 'Received from customer')], max_length=10)),
                ('cheque_no', models.CharField(max_length=20)),
                ('cheque_date', models.DateField(db_index=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DEPOSITED', 'Deposited'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.party')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('debit', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('IGNORED', 'Ignored')], default='UNMATCHED', max_length=10)),
                ('matched_journal_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_matches', to='ledger.journalline')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='banking.bankstatement')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'date'], name='banking_ban_status_ac5519_idx')],
            },
        ),
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=6, help_text='1 unit of currency = this many INR', max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('company', 'currency', 'date')},
            },
        ),
    ]
