# Generated by Django 5.0.6 on 2026-05-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdatedcheque',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
