# Generated by Django 5.1.4 on 2026-05-21 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompOffCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_date', models.DateField()),
                ('days_earned', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_offs', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'comp_off_credits',
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_calendars', to='tenants.tenant')),
            ],
            options={
                'db_table': 'holiday_calendars',
                'unique_together': {('tenant', 'year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('is_paid', models.BooleanField(default=True)),
                ('accrual_type', models.CharField(choices=[('upfront', 'Upfront (full year at start)'), ('monthly', 'Monthly accrual'), ('yearly', 'Yearly accrual'), ('manual', 'Manual credit only')], default='upfront', max_length=20)),
                ('accrual_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_annual_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_carry_forward', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('min_notice_days', models.PositiveSmallIntegerField(default=0)),
                ('max_consecutive_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requires_document_after', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('applicable_gender', models.CharField(choices=[('all', 'All'), ('male', 'Male Only'), ('female', 'Female Only')], default='all', max_length=10)),
                ('applicable_after_months', models.PositiveSmallIntegerField(default=0)),
                ('allow_half_day', models.BooleanField(default=True)),
                ('include_holidays', models.BooleanField(default=False)),
                ('include_weekends', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='tenants.tenant')),
            ],
            options={
                'db_table': 'leave_types',
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('holiday_date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('national', 'National'), ('regional', 'Regional'), ('optional', 'Optional'), ('restricted', 'Restricted')], default='national', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='leaves.holidaycalendar')),
            ],
            options={
                'db_table': 'holidays',
                'indexes': [models.Index(fields=['calendar', 'holiday_date'], name='holidays_calenda_5c6408_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=1, max_digits=4)),
                ('half_day_type', models.CharField(blank=True, choices=[('', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half')], max_length=15)),
                ('reason', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='leave_docs/%Y/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='tenants.tenant')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype')),
            ],
            options={
                'db_table': 'leave_requests',
                'indexes': [models.Index(fields=['employee', 'status'], name='leave_reque_employe_fd03a1_idx'), models.Index(fields=['tenant', 'from_date'], name='leave_reque_tenant__299d98_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('credited', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taken', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('adjusted', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carry_forward', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype')),
            ],
            options={
                'db_table': 'leave_balances',
                'indexes': [models.Index(fields=['employee', 'year'], name='leave_balan_employe_ee6624_idx')],
                'unique_together': {('tenant', 'employee', 'leave_type', 'year')},
            },
        ),
    ]
