# Generated by Django 5.1.4 on 2026-06-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreceipt',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalreceipt',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='1 unit of `currency` = this many base-currency units. 1 when currency == base.', max_digits=18),
        ),
        migrations.AddField(
            model_name='receipt',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='receipt',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='1 unit of `currency` = this many base-currency units. 1 when currency == base.', max_digits=18),
        ),
    ]
