# Generated by Django 5.1.4 on 2026-05-21 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cycle_type', models.CharField(choices=[('annual', 'Annual'), ('half_yearly', 'Half-Yearly'), ('quarterly', 'Quarterly'), ('probation', 'Probation'), ('project', 'Project-based')], default='annual', max_length=20)),
                ('review_period_start', models.DateField(help_text='Performance window — start of the period being reviewed')),
                ('review_period_end', models.DateField(help_text='Performance window — end')),
                ('opens_at', models.DateField(help_text='When managers can start writing reviews')),
                ('closes_at', models.DateField(help_text='When reviews must be submitted by')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active — reviews in progress'), ('review', 'Manager Review'), ('calibration', 'HR Calibration'), ('closed', 'Closed')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cycles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'review_cycles',
                'ordering': ['-review_period_end'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 — Below Expectations'), (2, '2 — Needs Improvement'), (3, '3 — Meets Expectations'), (4, '4 — Exceeds Expectations'), (5, '5 — Outstanding')], null=True)),
                ('technical_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 — Below Expectations'), (2, '2 — Needs Improvement'), (3, '3 — Meets Expectations'), (4, '4 — Exceeds Expectations'), (5, '5 — Outstanding')], help_text='Skill, expertise, output quality', null=True)),
                ('communication_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 — Below Expectations'), (2, '2 — Needs Improvement'), (3, '3 — Meets Expectations'), (4, '4 — Exceeds Expectations'), (5, '5 — Outstanding')], help_text='Clarity, responsiveness, collaboration', null=True)),
                ('ownership_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 — Below Expectations'), (2, '2 — Needs Improvement'), (3, '3 — Meets Expectations'), (4, '4 — Exceeds Expectations'), (5, '5 — Outstanding')], help_text='Initiative, accountability, follow-through', null=True)),
                ('teamwork_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 — Below Expectations'), (2, '2 — Needs Improvement'), (3, '3 — Meets Expectations'), (4, '4 — Exceeds Expectations'), (5, '5 — Outstanding')], help_text='Collaboration, mentorship, team spirit', null=True)),
                ('key_achievements', models.TextField(blank=True, help_text='Top accomplishments during the review period')),
                ('strengths', models.TextField(blank=True, help_text='What the employee does well')),
                ('areas_for_improvement', models.TextField(blank=True, help_text='Where the employee should grow')),
                ('goals_next_period', models.TextField(blank=True, help_text='Goals for the next cycle')),
                ('manager_comments', models.TextField(blank=True, help_text='Overall manager remarks')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Employee'), ('acknowledged', 'Acknowledged by Employee')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('employee_comments', models.TextField(blank=True, help_text="Employee's response after acknowledging")),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='employees.employee')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_written', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.reviewcycle')),
            ],
            options={
                'db_table': 'performance_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'employee')},
            },
        ),
    ]
