# Generated by GitHub Copilot on 2026-05-27

import django.db.models.deletion
from django.db import migrations, models


def seed_existing_fin_entitlements(apps, schema_editor):
    Plan = apps.get_model("saas", "Plan")
    Subscription = apps.get_model("saas", "Subscription")
    SubscriptionEntitlement = apps.get_model("saas", "SubscriptionEntitlement")
    Tenant = apps.get_model("core", "Tenant")

    legacy_plan, _ = Plan.objects.get_or_create(
        code="legacy-fin",
        defaults={
            "name": "Legacy FIN",
            "description": "Backfilled FIN access for tenants created before product entitlements.",
            "features": {"products": ["FIN"]},
            "is_active": True,
        },
    )

    for tenant in Tenant.objects.exclude(schema_name="public").filter(is_active=True).iterator():
        subscription, _ = Subscription.objects.get_or_create(
            tenant=tenant,
            defaults={"plan": legacy_plan, "status": "ACTIVE"},
        )
        SubscriptionEntitlement.objects.get_or_create(
            subscription=subscription,
            product="FIN",
            defaults={"status": subscription.status},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionEntitlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.CharField(choices=[("FIN", "Finance"), ("HR", "HRMS")], max_length=10)),
                ("status", models.CharField(choices=[("TRIAL", "Trial"), ("ACTIVE", "Active"), ("PAST_DUE", "Past Due"), ("SUSPENDED", "Suspended"), ("CANCELLED", "Cancelled")], default="TRIAL", max_length=12)),
                ("external_product_tenant_id", models.CharField(blank=True, help_text="Optional tenant/customer id in the separate product system.", max_length=100)),
                ("current_period_end", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entitlements", to="saas.subscription")),
            ],
            options={
                "unique_together": {("subscription", "product")},
            },
        ),
        migrations.RunPython(seed_existing_fin_entitlements, migrations.RunPython.noop),
    ]