# Generated by Django 5.1.4 on 2026-05-21 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.SlugField(max_length=100, unique=True)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='trial', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('country', models.CharField(default='IN', max_length=2)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('logo_url', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('cin', models.CharField(blank=True, max_length=21)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('max_employees', models.PositiveIntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_settings',
                'unique_together': {('tenant', 'key')},
            },
        ),
    ]
