# Generated by GitHub Copilot on 2026-05-27

import uuid
import django.db.models.deletion
from django.db import migrations, models


def seed_existing_hr_entitlements(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    ProductEntitlement = apps.get_model("tenants", "ProductEntitlement")

    for tenant in Tenant.objects.filter(status__in=["active", "trial"]).iterator():
        ProductEntitlement.objects.get_or_create(
            tenant=tenant,
            product="HR",
            defaults={"status": tenant.status},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_tan"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="customer_uid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name="ProductEntitlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product", models.CharField(choices=[("FIN", "Finance"), ("HR", "HRMS")], default="HR", max_length=10)),
                ("status", models.CharField(choices=[("trial", "Trial"), ("active", "Active"), ("past_due", "Past Due"), ("suspended", "Suspended"), ("cancelled", "Cancelled")], default="trial", max_length=20)),
                ("external_subscription_id", models.CharField(blank=True, max_length=100)),
                ("current_period_start", models.DateField(blank=True, null=True)),
                ("current_period_end", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_entitlements", to="tenants.tenant")),
            ],
            options={
                "db_table": "tenant_product_entitlements",
                "unique_together": {("tenant", "product")},
            },
        ),
        migrations.RunPython(seed_existing_hr_entitlements, migrations.RunPython.noop),
    ]